import crypto from "node:crypto";
import AfricasTalking from "africastalking";
import { db } from "@lastmile/db/client";
import { smsMessages } from "@lastmile/db/schemas/sms";
import { eq } from "drizzle-orm";

interface AfricasTalkingSMSResponse {
  SMSMessageData: {
    Message: string;
    Recipients: Array<{
      statusCode: number;
      number: string;
      status: string;
      cost: string;
      messageId: string;
    }>;
  };
}

interface AfricasTalkingSMSService {
  send(options: {
    to: string[];
    message: string;
    from?: string;
  }): Promise<AfricasTalkingSMSResponse>;
}

interface AfricasTalkingClient {
  SMS: AfricasTalkingSMSService;
}

// --- Credentials ---
const username = (process.env.AT_USERNAME ?? "sandbox").trim();
const apiKey = (process.env.AT_API_KEY ?? "").trim();

if (!apiKey) {
  console.warn("AT_API_KEY is not set — SMS dispatch will fail.");
}


const africasTalking = AfricasTalking({
  apiKey,
  username,
}) as AfricasTalkingClient;

const sms = africasTalking.SMS;

// --- Core dispatch primitive ---

/**
 * Sends a raw SMS to a single phone number.
 */
export async function dispatchAlert(
  phoneNumber: string,
  message: string,
): Promise<AfricasTalkingSMSResponse | null> {
  try {
    const response = await sms.send({ to: [phoneNumber], message });
    console.log(` Dispatched alert to ${phoneNumber} successfully.`);
    console.log(` SDK Response: ${JSON.stringify(response)}\n`);
    return response;
  } catch (err) {
    console.error(`Failed to dispatch to ${phoneNumber}:`, err);
    return null;
  }
}

/**
 * Sends a raw SMS to a single phone number and tracks it in the database.
 */
export async function dispatchAndTrackAlert(
  phoneNumber: string,
  message: string,
): Promise<AfricasTalkingSMSResponse | null> {
  const messageId = crypto.randomUUID();
  
  // Create pending record
  await db.insert(smsMessages).values({
    id: messageId,
    recipient: phoneNumber,
    content: message,
    status: "pending",
  });

  const response = await dispatchAlert(phoneNumber, message);
  
  // Update status based on response
  await db.update(smsMessages)
    .set({ status: response ? "sent" : "failed" })
    .where(eq(smsMessages.id, messageId));
    
  return response;
}

// --- Domain-specific helper ---

export interface OtpNotificationPayload {
  /** E.164 formatted phone number, e.g. "+254700000001" */
  phoneNumber: string;
  /** 4-digit account/transaction reference generated by the DB layer */
  refId: string;
  /** One-time pin to confirm the transaction/session */
  otp: string;
  /** Language preference of the user */
  preferredLanguage?: "en" | "sw" | "tu";
}

const otpSmsDictionary: Record<"en" | "sw" | "tu", (refId: string, otp: string) => string> = {
  en: (refId, otp) =>
    `SAPCONE LastMile: Your reference is ${refId}. Your OTP is ${otp}. Do not share this code.`,
  sw: (refId, otp) =>
    `SAPCONE LastMile: Namba yako ya kumbukumbu ni ${refId}. OTP yako ni ${otp}. Usishiriki namba hii.`,
  tu: (refId, otp) =>
    `SAPCONE LastMile: Reference ID kon nge ${refId}. OTP kon nge ${otp}. Nyikinyak ng'itunga.`,
};

export async function sendOtpAlert(
  payload: OtpNotificationPayload,
): Promise<AfricasTalkingSMSResponse | null> {
  const { phoneNumber, refId, otp, preferredLanguage = "en" } = payload;

  if (!phoneNumber || !refId || !otp) {
    throw new Error("sendOtpAlert requires phoneNumber, refId, and otp to all be set");
  }

  const message = otpSmsDictionary[preferredLanguage](refId, otp);

  return dispatchAndTrackAlert(phoneNumber, message);
}
